name: "Build and push"
description: "Builds a Java project's Dockerfile and pushes the resulting Docker image to the registry"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - uses: "gradle/wrapper-validation-action@v1"

      - name: "Set up JDK 17"
        uses: "actions/setup-java@v2"
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"

      - name: "Build with Gradle"
        shell: "bash"
        run: "./gradlew clean shadowJar --no-daemon"

      - name: "Login to container registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Build and push"
        uses: "docker/build-push-action@v3"
        with:
          context: "."
          file: "./Dockerfile"
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
